website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, session, url_for, current_app
from flask_login import login_required, current_user
from sqlalchemy.sql import func
from .models import Note, Todo, User, Deck, Flashcard
from . import db
import json, random

views = Blueprint('views', __name__)

@views.app_context_processor
def inject_user():
    return dict(user=current_user)

@views.route('/', methods=['GET'])
@login_required
def index():
    return render_template("index.html", user=current_user)

@views.route('/timer', methods=['GET'])
@login_required
def timer():
    return render_template("timer.html", user=current_user)

@views.route('/todo', methods=['GET', 'POST'])
@login_required
def todo():
    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')

        if title and description:
            todo_item = Todo(title=title, description=description, user_id=current_user.id)
            db.session.add(todo_item)
            db.session.commit()
            flash('Todo item added!', category='success')
        else:
            flash('Please provide both a title and description for the todo item.', category='error')

    return render_template("todo.html", user=current_user)

@views.route('/delete-todo', methods=['POST'])
def delete_todo():
    todo = json.loads(request.data) 
    todoId = todo['todoId']
    todo = Todo.query.get(todoId) 
    if todo: 
        if todo.user_id == current_user.id: 
            db.session.delete(todo)
            db.session.commit()
    return jsonify({})

@views.route('/complete-todo', methods=['POST'])
def complete_todo():
    todo = json.loads(request.data) 
    todoId = todo['todoId']
    todo = Todo.query.get(todoId) 
    if todo: 
        if todo.user_id == current_user.id: 
            if todo.completed == False:
                todo.completed = True
                db.session.commit()
            else:
                todo.completed = False
                db.session.commit()
    return jsonify({})

@views.route('/notes', methods=['GET', 'POST'])
@login_required
def notes():
    if request.method == 'POST':
        title = request.form.get('noteTitle')
        description = request.form.get('noteDescription')
        if not title or not description:
            flash('Please fill in both title and description.', category='error')
        else:
            new_note = Note(title=title, data=description, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
        # Redirect to the same endpoint to refresh the page and fetch updated list of notes
        return redirect(url_for('views.notes'))

    # Fetch notes after handling POST to ensure the list includes any newly added notes
    notes = Note.query.filter_by(user_id=current_user.id).all()
    return render_template("notes.html", user=current_user, notes=notes)


@views.route('/delete-note/<int:note_id>', methods=['POST'])
@login_required
def delete_note(note_id):
    note = Note.query.get(note_id)
    if note:
        if note.user_id == current_user.id:  # Ensure that the current user owns the note
            db.session.delete(note)
            db.session.commit()
            flash('Note deleted!', category='success')
        else:
            flash('You do not have permission to delete this note.', category='error')
    else:
        flash('Note not found.', category='error')
    
    return redirect(url_for('views.notes'))


@views.route('/edit-note/<int:note_id>', methods=['POST'])
@login_required
def edit_note(note_id):
    note = Note.query.get(note_id)
    if note and note.user_id == current_user.id:
        title = request.form.get('noteTitle')
        description = request.form.get('noteDescription')
        if title:
            note.title = title
        if description:
            note.data = description
        db.session.commit()
        flash('Note updated successfully!', 'success')
    else:
        flash('Note not found or you do not have permission to edit this note.', 'error')
    return redirect(url_for('views.notes'))


@views.route('/study-decks', methods=['GET'])
@login_required
def study_decks():
    decks = Deck.query.filter_by(user_id=current_user.id).all()
    return render_template('decks/study_decks.html', decks=decks)

@views.route('/study-decks/new', methods=['GET', 'POST'])
@login_required
def new_deck():
    if request.method == 'POST':
        title = request.form.get('title')
        if title:
            new_deck = Deck(title=title, user_id=current_user.id)
            db.session.add(new_deck)
            db.session.commit()
            flash('New deck created!', category='success')
            return redirect(url_for('views.study_decks'))
    return render_template('decks/new_deck.html')

@views.route('/study-decks/<int:deck_id>', methods=['GET', 'POST'])
@login_required
def view_deck(deck_id):
    deck = Deck.query.get_or_404(deck_id)
    if request.method == 'POST':
        question = request.form.get('question')
        answer = request.form.get('answer')
        if question and answer:
            if len(question) > 900 or len(answer) > 900:
                flash('Question and Answer must be less than 900 characters.', category='error')
            else:
                flashcard = Flashcard(question=question, answer=answer, deck_id=deck.id)
                db.session.add(flashcard)
                db.session.commit()
                flash('Flashcard added!', category='success')
    flashcards = Flashcard.query.filter_by(deck_id=deck.id).all()
    return render_template('decks/view_deck.html', deck=deck, flashcards=flashcards)

@views.route('/study-decks/<int:deck_id>/quiz', methods=['GET'])
@login_required
def start_quiz(deck_id):
    deck = Deck.query.get_or_404(deck_id)
    flashcards = Flashcard.query.filter_by(deck_id=deck.id).all()
    if flashcards:
        random.shuffle(flashcards)
    return render_template('decks/start_quiz.html', flashcards=flashcards)

@views.route('/study-decks/<int:deck_id>/delete-flashcard/<int:flashcard_id>', methods=['POST'])
@login_required
def delete_flashcard(deck_id, flashcard_id):
    flashcard = Flashcard.query.get_or_404(flashcard_id)
    if flashcard.deck_id == deck_id and flashcard.deck.user_id == current_user.id:
        db.session.delete(flashcard)
        db.session.commit()
        return jsonify({'success': 'Flashcard deleted'}), 200
    return jsonify({'error': 'Unauthorized'}), 403

@views.route('/study-decks/<int:deck_id>/delete', methods=['POST'])
@login_required
def delete_deck(deck_id):
    deck = Deck.query.get_or_404(deck_id)
    if deck.user_id == current_user.id:
        db.session.delete(deck)
        db.session.commit()
        return jsonify({'success': 'Deck deleted'}), 200
    return jsonify({'error': 'Unauthorized'}), 403

website/templates/index.html
{% extends "layout.html" %} {% block title %}Home{% endblock %} {% block content
%}
<head>
    <link rel="stylesheet" href="../static/css/index.css">
</head>
<h1 align="center" class="text-textD">码农万岁</h1>
{% endblock %}

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/focusIcon.png') }}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@600&amp;display=swap"
      rel="stylesheet"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"/>
    <title>{% block title %}Layout error{% endblock %}</title>
    <style>
      .flash-message {
        width: 100%;
        position: fixed;
        top: 76px; /* Adjusted to be 20px below the navbar */
        left: 0;
        z-index: 1050; /* Ensure it is above other content */
        opacity: 0.9;
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding-right: 1rem; /* Add some padding to the right for the close button */
      }
      .alert-error {
        background-color: red;
        color: white;
      }
    </style>
  </head>
  <body style="">
    <!-- ----------------------------NAVBAR------------------------------------ -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="../static/images/focusLogo5.png" alt="Your Company" style="height: 40px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/timer">Timer</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/notes">Notes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/todo">Todo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/study-decks">Study Decks</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/register">Register</a>
            </li>
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">Sign out</a>
            </li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- ----------------------------SPOTIFY------------------------------------ -->
    <!-- <div id="spotify-player">
      <iframe
        src="https://open.spotify.com/embed/playlist/2L8Gm7T2aJvRj1ih03UeKv?utm_source=generator&theme=0"
        width="20%"
        height="150"
        frameborder="0"
        allowfullscreen=""
        allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
        class="ml-2"
        loading="lazy"
      ></iframe>
    </div> -->

    {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
        {% for category, message in messages %} 
          <div class="alert alert-{{ category }} flash-message" role="alert">
            <span>{{ message }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}

    <script src="../static/js/todo.js"></script>
    <script src="../static/js/flash.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script>
      document.addEventListener('click', function() {
        const flashMessages = document.querySelectorAll('.flash-message');
        flashMessages.forEach(function(message) {
          message.style.display = 'none';
        });
      });
    </script>
  </body>
</html>

website/templates/login.html
{% extends "layout.html" %} {% block title %}Login{% endblock %} {% block content %}
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}"/>
</head>

<div class="login-container">
  <div class="wrapper">
    <form method="POST" class="flex flex-col items-center">
      <h1>Login</h1>
      <div class="input-box">
        <input type="email" placeholder="Email Address" id="email" name="email" required>
        <i class='bx bxs-user'></i>
      </div>
      <div class="input-box">
        <input type="password" placeholder="Password" id="password" name="password" required>
        <i class='bx bxs-lock-alt' ></i>
      </div>
      <button type="submit" class="btn">Login</button>
      <div class="register-link">
        <p>Dont have an account? <a href="/register">Register</a></p>
      </div>
    </form>
  </div>
</div>
{% endblock %}

website/templates/notes.html
{% extends "layout.html" %} {% block title %} Notes {% endblock %} {% block content %}

<!-- Design heavily inspired by https://www.codingnepalweb.com/build-a-notes-app-in-html-css-javascript/ -->

<head>
  <link rel="stylesheet" href="../static/css/notes.css">
  <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
</head>

<div class="popup-box">
  <div class="popup">
    <div class="content">
      <header>
        <p></p>
        <i class="uil uil-times"></i>
      </header>
      <form action="" method="POST">
        <div class="row title">
          <label>Title</label>
          <input type="text" id="noteTitle" name="noteTitle" spellcheck="false">
        </div>
        <div class="row description">
          <label>Description</label>
          <textarea id="noteDescription" name="noteDescription" spellcheck="false"></textarea>
        </div>
        <button type="submit" class="btn">Submit</button>
      </form>
    </div>
  </div>
</div>
<div class="wrapper">
  <li class="add-box">
    <div class="icon"><i class="uil uil-plus"></i></div>
    <p>Add new note</p>
  </li>
  {% for note in notes %}
  <li class="note">
    <div class="details">
      <p>{{ note.title }}</p>
      <span>{{ note.data | replace('\n', '<br>') | safe }}</span>
    </div>
    <div class="bottom-content">
      <span>{{ note.date.strftime('%Y-%m-%d %H:%M') }}</span>
      <div class="settings">
        <i onclick="showMenu(this)" class="uil uil-ellipsis-h"></i>
        <ul class="menu">
          <li onclick="editNote({{ note.id }}, '{{ note.title }}', '{{ note.data | replace('\n', '<br>') | safe }}')"><i class="uil uil-pen"></i>Edit</li>
            <form action="{{ url_for('views.delete_note', note_id=note.id) }}" method="POST" style="display: inline;">
              <input type="hidden" name="note_id" value="{{ note.id }}">
              <button type="submit" class="delete-button li-button">
                <i class="uil uil-trash"></i>Delete
              </button>
            </form>
        </ul>
      </div>
    </div>
  </li>
  {% endfor %}
</div>

<script src="../static/js/notes.js"></script>

{% endblock %}

website/templates/register.html
{% extends "layout.html" %} {% block title %}Register{% endblock %} {% block
content %}

<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}"/>
</head>

<div class="login-container">
  <div class="wrapper">
    <form method="POST" class="flex flex-col items-center">
      <h1>Register</h1>
      <div class="input-box">
        <input type="email" placeholder="Email Address" id="email" name="email" required>
        <i class='bx bxs-user'></i>
      </div>
      <!-- <div class="input-box">
        <input type="text" placeholder="Username" id="username" name="username" required>
        <i class='bx bxs-user'></i>
      </div> -->
      <div class="input-box">
        <input type="password" placeholder="Password" id="password" name="password" required>
        <i class='bx bxs-lock-alt' ></i>
      </div>
      <div class="input-box">
        <input type="password" placeholder="Password" id="confirm" name="confirm" required>
        <i class='bx bxs-lock-alt' ></i>
      </div>
      <button type="submit" class="btn">Register</button>
      <div class="register-link">
        <p>Already have an account? <a href="/login">Login</a></p>
      </div>
    </form>
  </div>
</div>

{% endblock %}

website/templates/timer.html
{% extends "layout.html" %} {% block title %}Timer{% endblock %} {% block
content %}
<head>
  <link rel="stylesheet" href="./static/css/timer.css" />
</head>

<body class="callout-open">
  <div id="pomodoro-container">
    <div id="pomodoro-durations">
      <div class="form-check">
        <input
          class="form-check-input"
          type="radio"
          name="timerType"
          id="exampleRadios1"
          value="pomodoro"
          checked=""
        />
        <label class="form-check-label btn" for="exampleRadios1">
          Pomodoro
        </label>
        <div class="pomo-counter">&nbsp;</div>
      </div>
      <div class="form-check">
        <input
          class="form-check-input"
          type="radio"
          name="timerType"
          id="exampleRadios2"
          value="short"
        />
        <label class="form-check-label btn" for="exampleRadios2">
          Short Break
        </label>
      </div>
      <div class="form-check">
        <input
          class="form-check-input"
          type="radio"
          name="timerType"
          id="exampleRadios3"
          value="long"
        />
        <label class="form-check-label btn" for="exampleRadios3">
          Long Break
        </label>
      </div>
    </div>

    <div id="pomodoro-timer">25:00</div>

    <div id="pomodoro-clock-actions">
      <button id="pomodoro-start" class="btn btn-primary">
        <span id="play-icon">start</span>
        <span class="hidden" id="pause-icon">pause</span>
      </button>
      <button id="pomodoro-stop" class="no-style bg-transparent">
        <svg
          version="1.1"
          id="Layer_1"
          xmlns=""
          xmlns:xlink=""
          x="0px"
          y="0px"
          viewBox="0 0 50 50"
          style="enable-background: new 0 0 50 50"
          xml:space="preserve"
        >
          <style type="text/css">
            .st0 {
              fill: #ffffff;
            }
          </style>
          <path
            class="st0"
            d="M48.3,3.4c-0.6-0.3-1.3-0.1-1.8,0.3L42.4,8l-0.6-0.5C37.3,3.1,31.3,0.7,25,0.7c0,0,0,0,0,0
                      c-6.5,0-12.6,2.5-17.2,7.1C3.2,12.4,0.7,18.5,0.7,25c0,6.5,2.5,12.6,7.1,17.2c4.6,4.6,10.7,7.1,17.2,7.1c6,0,11.8-2.2,16.3-6.3
                      c0.1-0.1,0.1-0.2,0.1-0.3c0-0.1,0-0.2-0.1-0.3l-4-4c-0.2-0.2-0.4-0.2-0.5,0c-3.2,2.9-7.4,4.4-11.7,4.4c-4.8,0-9.3-1.9-12.6-5.2
                      c-3.3-3.3-5.2-7.8-5.2-12.4c0-4.8,1.8-9.3,5.2-12.7C15.8,9,20.2,7.2,25,7.2c0,0,0.1,0,0.1,0c4.5,0,8.7,1.7,12,4.8l0.6,0.6L33,17.4
                  c-0.5,0.5-0.6,1.1-0.3,1.8c0.3,0.6,0.8,1,1.5,1h13.6c0.9,0,1.6-0.7,1.6-1.6V4.9C49.3,4.3,48.9,3.7,48.3,3.4z"
          ></path>
        </svg>
      </button>
    </div>
  </div>
</body>
<script src="./static/js/timer.js"></script>
{% endblock %}

website/templates/todo.html
{% extends "layout.html" %} {% block title %}Todo{% endblock %} {% block content %}
<div class="container p-4">
  <div class="row">
    <div class="col-md-6">
      <div class="mb-4">
        <form id="form-Task" method="POST">
          <div class="form-group">
            <input
              type="text"
              id="title"
              name="title"
              class="form-control"
              maxlength="50"
              autocomplete="off"
              placeholder="Title"
              required
            />
          </div>
          <div class="form-group mt-4">
            <textarea
              id="description"
              name="description"
              class="form-control"
              rows="10"
              maxlength="500"
              autocomplete="off"
              placeholder="Description"
              required
            ></textarea>
          </div>
          <div class="form-group mt-3">
            <button
              type="submit"
              class="button-30"
              style="width: 100%;"
            >
              Save
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <div class="d-flex justify-content-center p-2 bg-white rounded">
          <span class="font-weight-bold">Tasks</span>
          <!-- <span class="font-weight-bold">Description</span>
          <span class="font-weight-bold text-right">Delete</span> -->
        </div>
        <hr />
        <div class="overflow-y-scroll no-scrollbar todo-container px-4" style="height: 49rem">
          {% for todo in user.todo %}
          <div class="card todo-card my-3">
            <div class="card-body todo-card-body">
              <div class="todo-title">
                <p>{{ todo.title }}</p>
              </div>
              <div class="todo-description">
                <p><span>&#8226;</span> {{ todo.description }}</p>
              </div>
              <div class="todo-actions">
                {% if todo.completed %}
                <button onclick="completeTodo('{{ todo.id }}')" class="button-30-good-s">
                  <span>&check;</span>
                </button>
                {% else %}
                <button onclick="completeTodo('{{ todo.id }}')" class="button-30-s">
                  <span>&check;</span>
                </button>
                {% endif %}
                <button onclick="deleteTodo('{{ todo.id }}')" class="button-30-bad-s" style="margin-left: 5px;">
                  <span>X</span>
                </button>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}